version: '3.8'

services:
  web:
    image: aatikah/vul-djangoapp:latest  # Use your Docker Hub repository
    container_name: vul_djangoapp
    working_dir: /taskManager
    build:
      context: .
      dockerfile: Dockerfile  # Ensure you have a Dockerfile in your repo for building the image
    volumes:
      - .:/taskManager  # Mount the current directory to the container's working directory
    environment:
      - DJANGO_SETTINGS_MODULE=taskManager.settings
      - DEBUG=True
    ports:
      - "8000:8000"
    command: >
      bash -c "
      pip install --no-cache-dir -r taskManager/requirements.txt &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"

