version: '3.8'

services:
  web:
    image: python:3.9-slim  # Use the official Python image
    container_name: vul_djangoapp
    working_dir: /taskManager
    volumes:
      - .:/taskManager  # Mount the current directory to the container's working directory
    environment:
      - DJANGO_SETTINGS_MODULE=taskManager.settings
      - DEBUG=True
    ports:
      - "8000:8000"
    command: >
      bash -c "
      pip install --no-cache-dir -r requirements.txt &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
